log:
  show: 1
  level: 10
common:
  start: "9:30"
  eod: "15:25"
  live: 0
  base: BANKNIFTY
  exchange: NFO
supertrend:
  atr: 1
  multiplier: 2.1
BANKNIFTY:
  bexpiry: 24JUN
  sexpiry: 24JUL
  bdiff: -1
  sdiff: -1
  quantity: 15
  brick: 49
  nse: "NIFTY BANK"
